// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFhkHD6T69Y2jHxIrnS5pp6983qrPw0w4',
    appId: '1:1014464354077:web:c7f20d41cc2180c26633f4',
    messagingSenderId: '1014464354077',
    projectId: 'usverse-dev',
    authDomain: 'usverse-dev.firebaseapp.com',
    storageBucket: 'usverse-dev.firebasestorage.app',
    measurementId: 'G-J4NLPGTH7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCZIcr8AJ6L1MX-nbxK90yVHKzrcH8sGI',
    appId: '1:1014464354077:android:44a82c6aeb0d24b36633f4',
    messagingSenderId: '1014464354077',
    projectId: 'usverse-dev',
    storageBucket: 'usverse-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSa7rew44vvcyElUy5YHuxEWbrVdWKymo',
    appId: '1:1014464354077:ios:fbb0b0221857a72f6633f4',
    messagingSenderId: '1014464354077',
    projectId: 'usverse-dev',
    storageBucket: 'usverse-dev.firebasestorage.app',
    iosBundleId: 'com.usverse.usverse',
  );
}
