// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1X_eyTEHwKkqrGnU9wesinKnSN4XcNIY',
    appId: '1:104851831863:web:36c5f6baf9b3aeb326d3b2',
    messagingSenderId: '104851831863',
    projectId: 'usverse-platform',
    authDomain: 'usverse-platform.firebaseapp.com',
    storageBucket: 'usverse-platform.firebasestorage.app',
    measurementId: 'G-M9QWTGFTMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXbr6MiEvdPwQNtQ-H93YF--1XMxBVxHc',
    appId: '1:104851831863:android:e52789c6701ab12126d3b2',
    messagingSenderId: '104851831863',
    projectId: 'usverse-platform',
    storageBucket: 'usverse-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxnA2AqMgxPlnVHTb8q2xb9rfoBN11C0I',
    appId: '1:104851831863:ios:b90572f1829235ae26d3b2',
    messagingSenderId: '104851831863',
    projectId: 'usverse-platform',
    storageBucket: 'usverse-platform.firebasestorage.app',
    iosBundleId: 'com.usverse.usverse',
  );
}
